### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by devashish2024**

### CODE REVIEW

**Comment by devashish2024** [comment]
Hey!! Did you've seen this site I made - https://github.com/LexkingOfficial/lexkingofficial.github.io ? https://lexkingofficial.github.io

**Comment by Sachiru-Perera** [comment]
Wow! What a cool site man!

**Comment by devashish2024** [comment]
That's used for my father's future for his business!!

**Comment by devashish2024** [comment]
NP!! It's made using the "Bootstrap 5" Technology and Google Icons and Google Fonts!! It's made possible with these!! in text coding.

**Pull request closed without merging**
